### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by quangvinh242003** [FoggYu/PartNet#2]
Thank you for your code. However, I can not find file with following error:
 File "/home/vinh/Desktop/PartNet-master/pytorch_ops/sampling/_ext/farthestpointsampling/__init__.py", line 3, in <module>
    from ._farthestpointsampling import lib as _lib, ffi as _ffi
ImportError: No module named 'pytorch_ops.sampling._ext.farthestpointsampling._farthestpointsampling'
 
can you upload ._farthestpointsampling?
Thank you!

**Comment by FoggYu** [comment]
please run build.py under ./pytorch_ops/sampling fold first.

**Comment by quangvinh242003** [comment]
I got it. Thank you very much!!!
