### ISSUE TITLE
sample selection criteria for partnet-symh dataset

### ISSUE THREAD

**Issue by lx1037** [FoggYu/PartNet#9]
Hi, fenggen

I noticed that there are 4045 samples of airplanes in the ShapeNet dataset, but only 630 samples in the PartNet dataset you released. Did you follow any specific criteria when selecting samples for the PartNet-Symh dataset?

Thank you!

Best regards,
ziyu

**Comment by lx1037** [comment]
Sorry, I have another question. Thank you for sharing your dataset creation process at [https://github.com/FENGGENYU/CVPR2019_PartNet/issues/5#issuecomment-1176861275], which is very helpful to me. I would also like to ask what method you used to do fine-grained part segmentation in step 1? Thank you very much!

**Comment by FENGGENYU** [comment]
The data in PartNet dataset are from previous work GRASS, not sampled from Stanford ShapeNet.

Data in PartNet-Symh dataset are from Stanford PartNet dataset.

Step 1 are usually done by mannual segmentation, such as maya and 3ds max.

**Comment by lx1037** [comment]
I see. Thanks a lot!
